<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dpm.Orders.Application\Dpm.Orders.Application.csproj" />
    <ProjectReference Include="..\Dpm.Orders.Contracts\Dpm.Orders.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
  </ItemGroup>

</Project>
