<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\Dpm.Identity.Application\Dpm.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\Dpm.Identity.Infrastructure\Dpm.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Marketplace\Dpm.Marketplace.Infrastructure\Dpm.Marketplace.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\Dpm.Catalog.Infrastructure\Dpm.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Files\Dpm.Files.Infrastructure\Dpm.Files.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\Dpm.Orders.Infrastructure\Dpm.Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Payments\Dpm.Payments.Infrastructure\Dpm.Payments.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ledger\Dpm.Ledger.Infrastructure\Dpm.Ledger.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Downloads\Dpm.Downloads.Infrastructure\Dpm.Downloads.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.1" />
    <PackageReference Include="FluentValidation" Version="11.9.2" />
  </ItemGroup>

</Project>
