<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Modules\Identity\Dpm.Identity.Api\Dpm.Identity.Api.csproj" />
    <ProjectReference Include="..\Modules\Marketplace\Dpm.Marketplace.Api\Dpm.Marketplace.Api.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Dpm.Catalog.Api\Dpm.Catalog.Api.csproj" />
    <ProjectReference Include="..\Modules\Files\Dpm.Files.Api\Dpm.Files.Api.csproj" />
    <ProjectReference Include="..\Dpm.SharedApi\Dpm.SharedApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.2" />
  </ItemGroup>

</Project>
