<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dpm.Downloads.Application\Dpm.Downloads.Application.csproj" />
    <ProjectReference Include="..\Dpm.Downloads.Infrastructure\Dpm.Downloads.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Dpm.SharedApi\Dpm.SharedApi.csproj" />
    <ProjectReference Include="..\..\Identity\Dpm.Identity.Contracts\Dpm.Identity.Contracts.csproj" />
  </ItemGroup>

</Project>
