<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dpm.Identity.Application\Dpm.Identity.Application.csproj" />
    <ProjectReference Include="..\Dpm.Identity.Infrastructure\Dpm.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Dpm.SharedApi\Dpm.SharedApi.csproj" />
  </ItemGroup>

</Project>
