<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dpm.Orders.Domain\Dpm.Orders.Domain.csproj" />
    <ProjectReference Include="..\..\Catalog\Dpm.Catalog.Contracts\Dpm.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\Files\Dpm.Files.Contracts\Dpm.Files.Contracts.csproj" />
    <ProjectReference Include="..\..\Marketplace\Dpm.Marketplace.Contracts\Dpm.Marketplace.Contracts.csproj" />
    <ProjectReference Include="..\..\Payments\Dpm.Payments.Contracts\Dpm.Payments.Contracts.csproj" />
  </ItemGroup>

</Project>
