<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dpm.Orders.Application\Dpm.Orders.Application.csproj" />
    <ProjectReference Include="..\Dpm.Orders.Infrastructure\Dpm.Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Dpm.SharedApi\Dpm.SharedApi.csproj" />
    <ProjectReference Include="..\..\Identity\Dpm.Identity.Contracts\Dpm.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\Payments\Dpm.Payments.Application\Dpm.Payments.Application.csproj" />
  </ItemGroup>

</Project>
